spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/spring_security?useUnicode=true&serverTimezone=Hongkong&characterEncoding=utf-8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true

  session:
    store-type: none

security:
  oauth2:
    client:
      client-id: root
      client-secret: root

server:
  servlet:
    session:
      timeout: 600


imooc:
  security:
    browser:
      loginPage: /index.html
      logoutPage: /logout.html
      loginType: JSON
      session:
        maximumSessions: 1
    oauth2:
      clients[0]:
        clientId: root
        clientSecret: root
        accessTokenValiditySeconds: 3600
      clients[1]:
        clientId: admin
        clientSecret: admin

#      remeberMeSeconds: 36000
#    code:
#      image:
#        width: 200
#        length: 6

#        url: /user,/user/*