spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/xc_course?useUnicode=true&serverTimezone=Hongkong&characterEncoding=utf-8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true

  session:
    store-type: none

imooc:
  security:
    browser:
      loginPage: /index.html
      loginType: JSON
    code:
      image:
        width: 200
        length: 6
        url: /user,/user/*