spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/spring_security?useUnicode=true&serverTimezone=Hongkong&characterEncoding=utf-8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true

  session:
    store-type: none

imooc:
  security:
    browser:
      loginPage: /index.html
      loginType: JSON
#      remeberMeSeconds: 36000
#    code:
#      image:
#        width: 200
#        length: 6
#        url: /user,/user/*